### ISSUE TITLE
USER STORY: Fisherman

### ISSUE THREAD

**Issue by Pierreslag** [Pierreslag/my-first-agile-project#5]
As a **hobby fisherman** I want to **catch different fish species** for **relaxing and enojment benefints**
# Acceptance Criteria:
- Identify good fishing spot
- Select and set up fishing gear
- Follow fishing regulations
# Tasks
- [ ] Research lokal fishing spots
- [ ] Acquire right fishing gear
- [ ] Research fishing regulations for area
