### ISSUE TITLE
USER STORY: Carpenter

### ISSUE THREAD

**Issue by Pierreslag** [Pierreslag/my-first-agile-project#6]
As a **carpenter** I want to **build a furniture** so that i can **save money for other projects**
# Acceptance Criteria:
- The furniture works as planned
- Lower cost then buying the furniture in store
- Complete withing reasonable time
# Tasks
- [ ] Research what kind of furniture
- [ ] Design plan
- [ ] Material cost research
- [ ] Set up workspace
- [ ] Follow design plan
- [ ] Apply nice finish to enchance visual and durability
