### ISSUE TITLE
USER STORY: Full Stack Software Developer Student

### ISSUE THREAD

**Issue by Pierreslag** [Pierreslag/my-first-agile-project#7]
As a **full stack software developer student** I want to **build a webapp** so that i can **test my newfound skills**
# Acceptance Criteria:
- Design and front end user interface
- Good working backend functions
- Retrive data to storage database
# Tasks
- [ ] Define project requirement
- [ ] Make wireframes and design
- [ ] Make front end with HTML,CSS and JS
- [ ] Construct back end with python
- [ ] Set up database
- [ ] Test functions
- [ ] Deploy webapp
- [ ] Maintain the app
